import {AGENTS} from "./config.js";
import {bindUI} from "./ui.js";

const THREE_URL="https://esm.sh/three@0.186.0";
const ORBIT_URL="https://esm.sh/three@0.186.0/examples/jsm/controls/OrbitControls.js";
const HEADS=["Orion","Maya","Luna","Atlas","Noah","Clara","Ada","Vera","Bruno"];
const ROOMS={
 strategy:{label:"ESTRATÉGIA",x:-20,z:-11,w:12,d:9,c:0x334765},orion:{label:"DIREÇÃO · ORION",x:-6,z:-11,w:10,d:9,c:0x41456a},content:{label:"CONTEÚDO & MARCA",x:6,z:-11,w:15,d:9,c:0x553f63},owner:{label:"SALA DO HIANTO",x:24,z:-11,w:14,d:10,c:0x46567c},
 growth:{label:"GROWTH",x:-20,z:2,w:12,d:9,c:0x34584f},web:{label:"WEB & WORDPRESS",x:-6,z:2,w:10,d:9,c:0x31566b},sales:{label:"VENDAS & CRM",x:6,z:2,w:15,d:9,c:0x66543a},
 ai:{label:"IA & AUTOMAÇÃO",x:-20,z:15,w:12,d:9,c:0x474e78},qa:{label:"QA & GOVERNANÇA",x:-6,z:15,w:10,d:9,c:0x66465d},infra:{label:"VPS & INFRA",x:6,z:15,w:15,d:9,c:0x465a41},meeting:{label:"SALA DE REUNIÃO · 12 LUGARES",x:24,z:8,w:22,d:17,c:0x4b614d}
};
const ACTIONS={strategy:["pesquisando mercado","organizando evidências"],orion:["coordenando handoffs","revisando Jobs"],content:["revisando conteúdo","criando material"],growth:["analisando aquisição","checando performance"],web:["revisando implementação","checando conversão"],sales:["atualizando pipeline","qualificando contexto"],ai:["orquestrando workflow","checando integração"],qa:["auditando evidências","validando entrega"],infra:["checando infraestrutura","revisando observabilidade"]};

function install3DUI(){
 const s=document.createElement("style");s.textContent=`.three-canvas{position:absolute;inset:0;width:100%;height:100%;display:block;cursor:grab}.three-canvas:active{cursor:grabbing}.three-loading,.three-error{position:absolute;inset:0;display:grid;place-content:center;color:#eef5ff;font:13px system-ui}.three-error{color:#ffb9b9}`;document.head.appendChild(s);
 const b=document.querySelector(".brand");if(b)b.innerHTML='<em>AGENCY OS</em> · LIVING OFFICE 3D';
 const h=document.querySelector(".hud-chip.controls");if(h)h.innerHTML='Arraste = <b>360°</b> · Scroll = <b>zoom</b> · Direito = <b>pan</b> · WASD = andar';
 const dock=document.querySelector(".command-dock");if(dock&&!document.querySelector("#heads3d")){const bt=document.createElement("button");bt.id="heads3d";bt.textContent="👥 Heads";bt.onclick=()=>{const i=document.querySelector("#globalCommand");i.value=HEADS.map(n=>"@"+n).join(" ")+" reunião com os heads";document.querySelector("#callMentioned")?.click();};dock.insertBefore(bt,dock.querySelector("#globalCommand"));}
}

class Office3D{
 constructor(T,OrbitControls){this.T=T;this.OrbitControls=OrbitControls;this.stage=document.querySelector("#gameStage");this.agents=new Map();this.homes=new Map();this.movers=[];this.meetingParticipants=new Set();this.keys=new Set();this.clock=new T.Clock();this.init();}
 mat(c){return new this.T.MeshStandardMaterial({color:c,roughness:.82,metalness:.04});}
 box(w,h,d,c){const m=new this.T.Mesh(new this.T.BoxGeometry(w,h,d),this.mat(c));m.castShadow=m.receiveShadow=true;return m;}
 roomCenter(r){return new this.T.Vector3(r.x+r.w/2,0,r.z+r.d/2);}
 sprite(text,{bg="#0b1320",fg="#ffffff",w=3.2,h=.8,font=36}={}){const T=this.T,cv=document.createElement("canvas"),ctx=cv.getContext("2d");cv.width=512;cv.height=128;ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.fillStyle=fg;ctx.font=`700 ${font}px system-ui`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(text).slice(0,52),256,64,480);const tx=new T.CanvasTexture(cv);tx.colorSpace=T.SRGBColorSpace;const sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthTest:false}));sp.scale.set(w,h,1);sp.renderOrder=999;sp.userData.texture=tx;return sp;}
 bubble(name,text){const T=this.T,cv=document.createElement("canvas"),ctx=cv.getContext("2d"),words=String(text||"").split(/\s+/),lines=[];cv.width=768;cv.height=300;let line="";for(const word of words){const n=(line+" "+word).trim();if(n.length>44){lines.push(line);line=word}else line=n;if(lines.length===4)break;}if(line&&lines.length<5)lines.push(line);ctx.fillStyle="#f8fbff";ctx.fillRect(0,0,768,300);ctx.fillStyle="#245d9b";ctx.font="800 40px system-ui";ctx.fillText(name,28,54);ctx.fillStyle="#152438";ctx.font="600 34px system-ui";lines.forEach((l,i)=>ctx.fillText(l,28,112+i*42));const tx=new T.CanvasTexture(cv);tx.colorSpace=T.SRGBColorSpace;const sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthTest:false}));sp.scale.set(6.4,2.5,1);sp.renderOrder=1000;sp.userData.texture=tx;return sp;}
 init(){const T=this.T;this.scene=new T.Scene();this.scene.background=new T.Color(0x101722);this.scene.fog=new T.Fog(0x101722,45,110);this.camera=new T.PerspectiveCamera(43,1,.1,180);this.camera.position.set(35,30,40);this.renderer=new T.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.domElement.className="three-canvas";this.stage.replaceChildren(this.renderer.domElement);this.controls=new this.OrbitControls(this.camera,this.renderer.domElement);this.controls.target.set(7,0,5);this.controls.enableDamping=true;this.controls.minDistance=8;this.controls.maxDistance=78;this.controls.minPolarAngle=.28;this.controls.maxPolarAngle=1.5;this.controls.zoomToCursor=true;this.controls.mouseButtons.LEFT=T.MOUSE.ROTATE;this.controls.mouseButtons.MIDDLE=T.MOUSE.DOLLY;this.controls.mouseButtons.RIGHT=T.MOUSE.PAN;this.scene.add(new T.HemisphereLight(0xddeaff,0x202631,2.1));const sun=new T.DirectionalLight(0xffffff,2.8);sun.position.set(-20,38,-10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=50;sun.shadow.camera.bottom=-50;this.scene.add(sun);this.buildWorld();this.buildAgents();this.buildPlayer();this.bindInput();this.resize();addEventListener("resize",()=>this.resize());addEventListener("agency:agent-action",e=>this.setAgentAction(e.detail?.agent,e.detail?.action));addEventListener("agency:external-action",e=>this.setAgentAction(e.detail?.agent,e.detail?.action));window.__agencyOfficeScene=this;this.focusRoom("owner");setInterval(()=>this.pulseActivity(),5500);this.animate();dispatchEvent(new CustomEvent("agency:log",{detail:{agent:"SYSTEM",action:"OFFICE_3D_READY",detail:"Three.js r186 · câmera 360° · reunião 12 lugares"}}));}
 buildWorld(){const T=this.T,ground=new T.Mesh(new T.PlaneGeometry(82,62),this.mat(0x17212d));ground.rotation.x=-Math.PI/2;ground.position.set(7,-.08,5);ground.receiveShadow=true;this.scene.add(ground);const grid=new T.GridHelper(82,41,0x344963,0x243347);grid.position.set(7,0,5);grid.material.opacity=.22;grid.material.transparent=true;this.scene.add(grid);for(const [id,r] of Object.entries(ROOMS)){const floor=this.box(r.w,.14,r.d,r.c);floor.position.set(r.x+r.w/2,.02,r.z+r.d/2);this.scene.add(floor);[[r.x+r.w/2,r.z+.08,r.w,.16],[r.x+.08,r.z+r.d/2,.16,r.d],[r.x+r.w-.08,r.z+r.d/2,.16,r.d]].forEach(([x,z,w,d])=>{const wall=this.box(w,3.1,d,0x667587);wall.position.set(x,1.55,z);this.scene.add(wall)});const lab=this.sprite(r.label,{w:Math.min(6,r.w*.46),h:.55,font:30});lab.position.set(r.x+r.w/2,3.7,r.z+.45);this.scene.add(lab);}this.buildFurniture();}
 desk(x,z){const g=new this.T.Group();const top=this.box(2.35,.18,1.1,0x895f3d);top.position.y=1.03;g.add(top);for(const sx of [-.9,.9])for(const sz of [-.36,.36]){const l=this.box(.11,1,.11,0x4b3324);l.position.set(sx,.5,sz);g.add(l)}const mon=this.box(.85,.55,.08,0x111a24);mon.position.set(0,1.52,-.25);g.add(mon);const sc=this.box(.69,.4,.025,0x367eb5);sc.position.set(0,1.53,-.295);g.add(sc);g.position.set(x,0,z);this.scene.add(g);}
 chair(x,z,rot=0){const g=new this.T.Group(),s=this.box(.82,.14,.82,0x465d79);s.position.y=.7;g.add(s);const b=this.box(.82,1,.12,0x465d79);b.position.set(0,1.15,.36);g.add(b);g.position.set(x,0,z);g.rotation.y=rot;this.scene.add(g);}
 table(x,z){const t=this.box(9.6,.24,3.8,0x876344);t.position.set(x,1,z);this.scene.add(t);for(const sx of [-3.6,3.6])for(const sz of [-1.25,1.25]){const l=this.box(.22,1,.22,0x4b3828);l.position.set(x+sx,.5,z+sz);this.scene.add(l)}}
 buildFurniture(){const oc=this.roomCenter(ROOMS.owner);this.desk(oc.x,oc.z-1.2);this.chair(oc.x,oc.z+.15,Math.PI);const sofa=this.box(3.5,.75,1.15,0x536f8e);sofa.position.set(oc.x-3.7,.45,oc.z+2.8);this.scene.add(sofa);const mc=this.roomCenter(ROOMS.meeting);this.table(mc.x,mc.z);this.meetingSeats=[];const seats=[[-3.6,-3,0],[-1.2,-3,0],[1.2,-3,0],[3.6,-3,0],[-3.6,3,Math.PI],[-1.2,3,Math.PI],[1.2,3,Math.PI],[3.6,3,Math.PI],[-5.7,-1.25,Math.PI/2],[-5.7,1.25,Math.PI/2],[5.7,-1.25,-Math.PI/2],[5.7,1.25,-Math.PI/2]];seats.forEach(([dx,dz,rot])=>{this.chair(mc.x+dx,mc.z+dz,rot);this.meetingSeats.push({x:mc.x+dx,z:mc.z+dz,rot})});this.stations={};for(const dept of ["strategy","orion","content","growth","web","sales","ai","qa","infra"]){const r=ROOMS[dept],list=AGENTS.filter(a=>a.dept===dept),cols=Math.min(3,Math.max(1,Math.ceil(Math.sqrt(list.length)))),rows=Math.ceil(list.length/cols),sx=r.w/(cols+1),sz=r.d/(rows+1);this.stations[dept]=list.map((a,i)=>{const x=r.x+sx*((i%cols)+1),z=r.z+sz*(Math.floor(i/cols)+1);this.desk(x,z-.15);this.chair(x,z+1,Math.PI);return{name:a.name,x,z:z+1,rot:Math.PI}});}}
 color(name){const p=[0x4f8edc,0x8a63d2,0x3e9d78,0xd07b55,0xd0a34b,0x5f78c9,0xb85f7c,0x4d9ca7];let h=0;for(const ch of name)h=((h<<5)-h)+ch.charCodeAt(0);return p[Math.abs(h)%p.length];}
 person(name,c,isPlayer=false){const T=this.T,g=new T.Group();g.userData.name=name;const torso=this.box(.72,1.05,.42,c);torso.position.y=1.6;g.add(torso);const head=new T.Mesh(new T.SphereGeometry(.34,16,12),this.mat(0xe6b28d));head.position.y=2.42;head.castShadow=true;g.add(head);const armL=this.box(.18,.9,.18,c),armR=armL.clone();armL.position.set(-.47,1.55,0);armR.position.set(.47,1.55,0);g.add(armL,armR);const thighL=this.box(.24,.75,.25,0x33465d),thighR=thighL.clone(),shinL=this.box(.22,.72,.22,0x2c3d51),shinR=shinL.clone();g.add(thighL,thighR,shinL,shinR);const label=this.sprite(name,{w:2.4,h:.5,font:35});label.position.set(0,3.12,0);g.add(label);g.userData.parts={torso,head,armL,armR,thighL,thighR,shinL,shinR};this.pose(g,"stand");return g;}
 pose(g,p){const q=g.userData.parts;if(!q)return;if(p==="sit"){q.torso.position.y=1.34;q.head.position.y=2.16;q.armL.position.y=q.armR.position.y=1.31;q.thighL.rotation.x=q.thighR.rotation.x=Math.PI/2;q.thighL.position.set(-.2,.72,-.28);q.thighR.position.set(.2,.72,-.28);q.shinL.position.set(-.2,.35,-.64);q.shinR.position.set(.2,.35,-.64)}else{q.torso.position.y=1.6;q.head.position.y=2.42;q.armL.position.y=q.armR.position.y=1.55;q.thighL.rotation.x=q.thighR.rotation.x=0;q.thighL.position.set(-.2,.72,0);q.thighR.position.set(.2,.72,0);q.shinL.position.set(-.2,.25,0);q.shinR.position.set(.2,.25,0)}g.userData.pose=p;}
 buildAgents(){for(const a of AGENTS){const h=(this.stations[a.dept]||[]).find(x=>x.name===a.name);if(!h)continue;const g=this.person(a.name,this.color(a.name));g.position.set(h.x,0,h.z);g.rotation.y=h.rot;this.pose(g,"sit");this.scene.add(g);this.agents.set(a.name,g);this.homes.set(a.name,h);}}
 buildPlayer(){const c=this.roomCenter(ROOMS.owner);this.player=this.person("HIANTO",0x4d8df5,true);this.player.position.set(c.x-1.4,0,c.z+1.2);this.scene.add(this.player);}
 bindInput(){const T=this.T,ray=new T.Raycaster(),p=new T.Vector2();let down=null;this.renderer.domElement.addEventListener("pointerdown",e=>down={x:e.clientX,y:e.clientY});this.renderer.domElement.addEventListener("pointerup",e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5){down=null;return}down=null;const r=this.renderer.domElement.getBoundingClientRect();p.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(p,this.camera);const hits=ray.intersectObjects([...this.agents.values()],true);if(hits[0]){let o=hits[0].object;while(o.parent&&!o.userData.name)o=o.parent;const a=AGENTS.find(x=>x.name===o.userData.name);if(a)this.openAgent(a)}});addEventListener("keydown",e=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;this.keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==="e"){const a=this.nearestAgent();if(a)this.openAgent(a)}if(e.key.toLowerCase()==="r")this.focusRoom("owner")});addEventListener("keyup",e=>this.keys.delete(e.key.toLowerCase()));}
 updatePlayer(dt){const d=new this.T.Vector3();if(this.keys.has("w")||this.keys.has("arrowup"))d.z--;if(this.keys.has("s")||this.keys.has("arrowdown"))d.z++;if(this.keys.has("a")||this.keys.has("arrowleft"))d.x--;if(this.keys.has("d")||this.keys.has("arrowright"))d.x++;if(d.lengthSq()){d.normalize();this.player.position.addScaledVector(d,5.2*dt);this.player.rotation.y=Math.atan2(d.x,d.z)}}
 step(dx,dy){this.player.position.x+=dx*.9;this.player.position.z+=dy*.9;}
 nearestAgent(){let best=null,d=1e9;for(const a of AGENTS){const g=this.agents.get(a.name);if(!g)continue;const n=g.position.distanceTo(this.player.position);if(n<d){d=n;best=a}}return d<4?best:null;}
 openAgent(a){dispatchEvent(new CustomEvent("agency:open-agent",{detail:a}));this.showSpeech(a,"Oi, Hianto. O que vamos fazer?");this.setSelectedAgent(a);}
 setSelectedAgent(a){const g=this.agents.get(a?.name);if(g)this.controls.target.lerp(new this.T.Vector3(g.position.x,1,g.position.z),.55);}
 move(name,to,{duration=900,rot=null,pose="stand",done=null}={}){const g=this.agents.get(name);if(!g)return;this.pose(g,"stand");this.movers=this.movers.filter(m=>m.g!==g);this.movers.push({g,from:g.position.clone(),to:new this.T.Vector3(to.x,0,to.z),start:performance.now(),duration,rot,pose,done});}
 updateMovers(now){this.movers=this.movers.filter(m=>{const t=Math.min(1,(now-m.start)/m.duration),e=1-Math.pow(1-t,3);m.g.position.lerpVectors(m.from,m.to,e);const dx=m.to.x-m.from.x,dz=m.to.z-m.from.z;if(t<1)m.g.rotation.y=Math.atan2(dx,dz);if(t>=1){if(m.rot!==null)m.g.rotation.y=m.rot;this.pose(m.g,m.pose);m.done?.();return false}return true});}
 focusRoom(id){const r=ROOMS[id]||ROOMS.owner,c=this.roomCenter(r),wide=id==="meeting",target=new this.T.Vector3(c.x,1,c.z),pos=new this.T.Vector3(c.x+(wide?18:12),wide?16:12,c.z+(wide?20:14));this.cam={s:performance.now(),fromP:this.camera.position.clone(),toP:pos,fromT:this.controls.target.clone(),toT:target};}
 updateCam(now){if(!this.cam)return;const t=Math.min(1,(now-this.cam.s)/650),e=1-Math.pow(1-t,3);this.camera.position.lerpVectors(this.cam.fromP,this.cam.toP,e);this.controls.target.lerpVectors(this.cam.fromT,this.cam.toT,e);if(t>=1)this.cam=null;}
 summonToMeeting(names=[]){const u=[...new Set(names)].filter(n=>this.agents.has(n)).slice(0,12);this.meetingParticipants=new Set(u);this.focusRoom("meeting");u.forEach((n,i)=>{const s=this.meetingSeats[i];this.setAgentAction(n,"indo para a reunião...");this.move(n,s,{duration:850+i*70,rot:s.rot,pose:"sit",done:()=>{this.setAgentAction(n,"em reunião");const a=AGENTS.find(x=>x.name===n);if(a)this.showSpeech(a,"Cheguei para a reunião.")}})});dispatchEvent(new CustomEvent("agency:log",{detail:{agent:"Orion",action:"MEETING_3D",detail:u.join(", ")}}));}
 summonToOwner(names=[]){const c=this.roomCenter(ROOMS.owner),s=[{x:c.x-3,z:c.z+.5},{x:c.x+3,z:c.z+.5},{x:c.x-3,z:c.z+2.6},{x:c.x+3,z:c.z+2.6}];this.focusRoom("owner");names.slice(0,4).forEach((n,i)=>this.move(n,s[i],{duration:850+i*80,done:()=>{const a=AGENTS.find(x=>x.name===n);if(a)this.showSpeech(a,"Hianto, cheguei à sua sala.")}}));}
 returnAgents(names=[]){names.forEach((n,i)=>{const h=this.homes.get(n);if(h)this.move(n,h,{duration:850+i*40,rot:h.rot,pose:"sit",done:()=>this.setAgentAction(n,"trabalhando")})});}
 endMeeting(){this.returnAgents([...this.meetingParticipants]);this.meetingParticipants.clear();this.focusRoom("owner");}
 showSpeech(a,text){const g=this.agents.get(a?.name);if(!g)return;if(g.userData.speech){g.remove(g.userData.speech);g.userData.speech.material.map.dispose();g.userData.speech.material.dispose()}const b=this.bubble(a.name,text);b.position.set(0,3.9,0);g.add(b);g.userData.speech=b;clearTimeout(g.userData.speechTimer);g.userData.speechTimer=setTimeout(()=>{if(g.userData.speech===b){g.remove(b);b.material.map.dispose();b.material.dispose();g.userData.speech=null}},9000);}
 setAgentAction(n,text=""){const g=this.agents.get(n);if(!g)return;if(g.userData.action){g.remove(g.userData.action);g.userData.action.material.map.dispose();g.userData.action.material.dispose()}if(!text)return;const s=this.sprite(text,{bg:"#153021",fg:"#bff0cf",w:3,h:.55,font:30});s.position.set(0,3.25,0);g.add(s);g.userData.action=s;clearTimeout(g.userData.actionTimer);g.userData.actionTimer=setTimeout(()=>{if(g.userData.action===s){g.remove(s);s.material.map.dispose();s.material.dispose();g.userData.action=null}},7000);}
 showHandoff(f,t,reason){const a=this.agents.get(f?.name),b=this.agents.get(t?.name);if(!a||!b)return;const geo=new this.T.BufferGeometry().setFromPoints([a.position.clone().setY(2.8),b.position.clone().setY(2.8)]),mat=new this.T.LineBasicMaterial({color:0xb88cff}),line=new this.T.Line(geo,mat);this.scene.add(line);this.showSpeech(f,`Passando para ${t.name}: ${reason}`);setTimeout(()=>{this.scene.remove(line);geo.dispose();mat.dispose()},3200);}
 pulseActivity(){const list=AGENTS.filter(a=>a.status==="working"&&this.agents.has(a.name));if(!list.length)return;const a=list[Math.floor(Math.random()*list.length)],arr=ACTIONS[a.dept]||["trabalhando"],action=arr[Math.floor(Math.random()*arr.length)];this.setAgentAction(a.name,action+"...");dispatchEvent(new CustomEvent("agency:agent-action",{detail:{agent:a.name,kind:"internal",action,task:a.task}}));}
 resize(){const w=this.stage.clientWidth||innerWidth,h=this.stage.clientHeight||innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
 animate(){requestAnimationFrame(()=>this.animate());const dt=Math.min(this.clock.getDelta(),.05),now=performance.now();this.updatePlayer(dt);this.updateMovers(now);this.updateCam(now);this.controls.update();this.renderer.render(this.scene,this.camera);}
}

async function boot(){install3DUI();const stage=document.querySelector("#gameStage");try{stage.innerHTML='<div class="three-loading">Inicializando Living Office 3D...</div>';const T=await import(THREE_URL),{OrbitControls}=await import(ORBIT_URL);window.__agencyGame=new Office3D(T,OrbitControls);bindUI()}catch(e){console.error(e);stage.innerHTML='<div class="three-error">Living Office 3D falhou: '+String(e?.message||e)+'</div>';try{bindUI()}catch{}}}
boot();
